package channel

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"sort"
	"strings"
)

// aur.go — AUR(Arch User Repository・owned)。ビルド済みバイナリの -bin パッケージとして
// PKGBUILD ＋ .SRCINFO を生成し、aur.archlinux.org の自前パッケージ git へ push する(設計 03)。
// 審査はなく自前 push(AUR_SSH_KEY)。実体照合は AUR RPC で版を引く。
//
// 実 push(git+ssh)は AurPusher(channel/aur_git.go)。ここは生成と RPC probe。

// AurSource は 1 アーキの配布(linux tarball)。
type AurSource struct {
	Arch   string // amd64 | arm64
	URL    string
	SHA256 string
}

// AurInput は PKGBUILD 生成の入力。
type AurInput struct {
	Package     string // AUR パッケージ名(既定 <project>-bin)
	Project     string // バイナリ名
	Version     string
	License     string
	Description string
	Homepage    string
	Maintainer  string
	Sources     []AurSource
}

// aurArch は goarch を Arch の arch に直す(amd64→x86_64 / arm64→aarch64)。
func aurArch(arch string) string {
	switch arch {
	case "amd64":
		return "x86_64"
	case "arm64":
		return "aarch64"
	}
	return arch
}

// sortedSources は arch 順に並べて生成を決定的にする。
func (in AurInput) sortedSources() []AurSource {
	s := append([]AurSource(nil), in.Sources...)
	sort.Slice(s, func(i, j int) bool { return aurArch(s[i].Arch) < aurArch(s[j].Arch) })
	return s
}

// GeneratePKGBUILD は -bin パッケージの PKGBUILD を生成する(決定的)。
func GeneratePKGBUILD(in AurInput) string {
	var b strings.Builder
	if in.Maintainer != "" {
		fmt.Fprintf(&b, "# Maintainer: %s\n", in.Maintainer)
	}
	fmt.Fprintf(&b, "# GENERATED BY wharfy — do not edit.\n")
	fmt.Fprintf(&b, "pkgname=%s\n", in.Package)
	fmt.Fprintf(&b, "pkgver=%s\n", in.Version)
	b.WriteString("pkgrel=1\n")
	fmt.Fprintf(&b, "pkgdesc=%q\n", in.Description)
	srcs := in.sortedSources()
	arches := make([]string, 0, len(srcs))
	for _, s := range srcs {
		arches = append(arches, "'"+aurArch(s.Arch)+"'")
	}
	fmt.Fprintf(&b, "arch=(%s)\n", strings.Join(arches, " "))
	fmt.Fprintf(&b, "url=%q\n", in.Homepage)
	fmt.Fprintf(&b, "license=('%s')\n", aurLicense(in.License))
	fmt.Fprintf(&b, "provides=('%s')\n", in.Project)
	fmt.Fprintf(&b, "conflicts=('%s')\n", in.Project)
	for _, s := range srcs {
		a := aurArch(s.Arch)
		fmt.Fprintf(&b, "source_%s=(\"%s-%s-%s.tar.gz::%s\")\n", a, in.Package, in.Version, a, s.URL)
		fmt.Fprintf(&b, "sha256sums_%s=('%s')\n", a, s.SHA256)
	}
	fmt.Fprintf(&b, "\npackage() {\n  install -Dm755 \"%s\" \"$pkgdir/usr/bin/%s\"\n}\n", in.Project, in.Project)
	return b.String()
}

// GenerateSRCINFO は PKGBUILD に対応する .SRCINFO を生成する(AUR は両方を要求)。
func GenerateSRCINFO(in AurInput) string {
	var b strings.Builder
	fmt.Fprintf(&b, "pkgbase = %s\n", in.Package)
	fmt.Fprintf(&b, "\tpkgdesc = %s\n", in.Description)
	fmt.Fprintf(&b, "\tpkgver = %s\n", in.Version)
	b.WriteString("\tpkgrel = 1\n")
	fmt.Fprintf(&b, "\turl = %s\n", in.Homepage)
	fmt.Fprintf(&b, "\tlicense = %s\n", aurLicense(in.License))
	for _, s := range in.sortedSources() {
		fmt.Fprintf(&b, "\tarch = %s\n", aurArch(s.Arch))
	}
	fmt.Fprintf(&b, "\tprovides = %s\n", in.Project)
	fmt.Fprintf(&b, "\tconflicts = %s\n", in.Project)
	for _, s := range in.sortedSources() {
		a := aurArch(s.Arch)
		fmt.Fprintf(&b, "\tsource_%s = %s-%s-%s.tar.gz::%s\n", a, in.Package, in.Version, a, s.URL)
		fmt.Fprintf(&b, "\tsha256sums_%s = %s\n", a, s.SHA256)
	}
	fmt.Fprintf(&b, "\npkgname = %s\n", in.Package)
	return b.String()
}

// Files は AUR git に置く {ファイル名: 内容}(PKGBUILD ＋ .SRCINFO)。
func (in AurInput) Files() map[string]string {
	return map[string]string{
		"PKGBUILD": GeneratePKGBUILD(in),
		".SRCINFO": GenerateSRCINFO(in),
	}
}

func aurLicense(l string) string {
	if l == "" {
		return "unknown"
	}
	return l
}

// AurPusher は AUR git(ssh)への push 境界。実装は git+ssh。テストは fake。
type AurPusher interface {
	Push(ctx context.Context, pkgname string, files map[string]string) (commit string, err error)
}

// AurProbe は AUR RPC で実体の版を引く(04 の実体照合)。
type AurProbe struct {
	Base string // 既定 https://aur.archlinux.org
	HTTP *http.Client
}

// Probe は AUR RPC v5 info で pkgname の版を返す(pkgrel は落とす)。無ければ found=false。
func (p *AurProbe) Probe(ctx context.Context, pkgname string) (RemoteState, error) {
	base := p.Base
	if base == "" {
		base = "https://aur.archlinux.org"
	}
	url := strings.TrimRight(base, "/") + "/rpc/v5/info/" + pkgname
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return RemoteState{}, err
	}
	cl := p.HTTP
	if cl == nil {
		cl = http.DefaultClient
	}
	resp, err := cl.Do(req)
	if err != nil {
		return RemoteState{}, err
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK {
		return RemoteState{}, fmt.Errorf("aur rpc %s: %s", url, resp.Status)
	}
	var out struct {
		Results []struct {
			Version string `json:"Version"`
		} `json:"results"`
	}
	if err := json.Unmarshal(body, &out); err != nil {
		return RemoteState{}, err
	}
	if len(out.Results) == 0 {
		return RemoteState{Found: false}, nil
	}
	return RemoteState{Version: stripPkgrel(out.Results[0].Version), Found: true}, nil
}

// stripPkgrel は AUR の "1.2.3-1" から pkgrel を落として "1.2.3" にする。
func stripPkgrel(v string) string {
	if i := strings.LastIndexByte(v, '-'); i > 0 {
		return v[:i]
	}
	return v
}
