package channel

import (
	"fmt"
	"strings"
)

// notice.go — 配布者が書いた告知を、各チャネルの注記欄へ逐語で運ぶ(D-3)。
//
// wharfy は文面を作らない。言い換えもしない。ここがするのは、生成先の構文で
// 壊れないように包むことだけ。包み方を間違えると配布物が壊れるので、そこは wharfy の責任。

// TrimNotice は告知の前後の空白を落とす。空なら "" を返す(呼び手は何も出さない)。
func TrimNotice(s string) string { return strings.TrimSpace(s) }

// noticeLines は告知を行の配列にする(scoop の notes 等、行配列を取る欄向け)。空なら nil。
func noticeLines(s string) []string {
	if s = TrimNotice(s); s == "" {
		return nil
	}
	return strings.Split(s, "\n")
}

// heredocTerminator は本文と衝突しないヒアドキュメント終端子を選ぶ。
// 行頭に終端子と同じ行があるとそこで文字列が切れ、生成物が壊れる。
func heredocTerminator(body, base string) string {
	term := base
	for attempt := 2; containsLine(body, term); attempt++ {
		term = fmt.Sprintf("%s%d", base, attempt)
	}
	return term
}

// containsLine は body に「その行だけ」が s と一致する行があるか(前後の空白は無視)。
func containsLine(body, s string) bool {
	for _, line := range strings.Split(body, "\n") {
		if strings.TrimSpace(line) == s {
			return true
		}
	}
	return false
}

// writeRubyCaveats は caveats を 1 つだけ書く(Ruby は後勝ちなので分割できない)。
// blocks は上から順に連結され、空要素は落ちる。
//
// 単一引用ヒアドキュメント(<<~'EOS')を使うのは、配布者の文面に #{...} があっても
// Ruby に式として評価させないため。文面は逐語で出す。
func writeRubyCaveats(b *strings.Builder, indent string, blocks ...string) {
	var kept []string
	for _, s := range blocks {
		if s = TrimNotice(s); s != "" {
			kept = append(kept, s)
		}
	}
	if len(kept) == 0 {
		return
	}
	body := strings.Join(kept, "\n\n")
	term := heredocTerminator(body, "EOS")
	fmt.Fprintf(b, "%scaveats <<~'%s'\n", indent, term)
	for _, line := range strings.Split(body, "\n") {
		if line == "" {
			b.WriteString("\n")
			continue
		}
		fmt.Fprintf(b, "%s  %s\n", indent, line)
	}
	fmt.Fprintf(b, "%s%s\n", indent, term)
}

// GenerateAurInstall は AUR の .install ファイルを生成する。
// pkgdesc は 1 行のシェル文字列なので複数行の告知を運べない。AUR の作法どおり
// post_install / post_upgrade で出す(pacman が install / upgrade のたびに表示する)。
//
// 単一引用ヒアドキュメント(<<'EOS')なので、文面の $var や `cmd` はシェルに評価されない。
func GenerateAurInstall(notice string) string {
	notice = TrimNotice(notice)
	if notice == "" {
		return ""
	}
	term := heredocTerminator(notice, "EOS")
	var b strings.Builder
	b.WriteString("# GENERATED BY wharfy — do not edit.\n")
	b.WriteString("post_install() {\n")
	fmt.Fprintf(&b, "  cat <<'%s'\n", term)
	b.WriteString(notice)
	fmt.Fprintf(&b, "\n%s\n", term)
	b.WriteString("}\n\n")
	b.WriteString("post_upgrade() {\n  post_install\n}\n")
	return b.String()
}
