// Package registry は能力の単一真実(能力レジストリ / drift 対策)。
//
// コマンド・要約・引数・既定 next: をここ 1 か所に持つ。cobra のコマンド登録も
// agent の一枚出力も「ここから生成」する。手書きの能力一覧は実体とズレるため持たない。
// 新コマンドはここに足すだけで agent 出力・補完・docs に自動で載る。
//
// 依存なし(純データ + 整形のみ)。下位層として上位を知らない(依存は上から下への一方向)。
package registry

import (
	"fmt"
	"strings"
)

// Command はレジストリの 1 エントリ。schemas/common.json の commandSpec と同形。
// agent --json の commands[] はこれの配列(出力契約)。
type Command struct {
	Name    string   `json:"name"`
	Summary string   `json:"summary"`
	Args    string   `json:"args,omitempty"`
	Next    []string `json:"next,omitempty"` // 既定の次コマンド名。参照先は必ず registry に実在する。
	// Notes はそのコマンドを駆動する前に知っておくべき注記(1 行 1 点)。
	// channelRef.notes と同じ狙い: 前提を知らずに叩くと壊れる類の事実を、能力マップの側で語る。
	Notes []string `json:"notes,omitempty"`
}

// ChannelRef は agent 出力でのチャネル参照。schemas/common.json の channelRef。
// Notes はそのチャネルを駆動する前に知っておくべき注記(1 行 1 点)。
type ChannelRef struct {
	Name  string   `json:"name"`
	Kind  string   `json:"kind"` // owned | gated (common.json channelKind)
	Notes []string `json:"notes,omitempty"`
}

// InstallExitCode は install.sh / install.ps1 が名乗る終了コードと、その意味。
//
// wharfy が所有する生成物の対外契約なので、ここが単一真実になる。生成物のヘッダ・
// agent 出力・README で別々に書けば必ずずれる(drift 対策)。
type InstallExitCode struct {
	Code    int
	Meaning string
}

// InstallExitCodes は script チャネルの生成物が名乗る終了コード。
//
// 3 つだけ意味を持たせ、残りは全部 1 に閉じ込める。閉じ込めないと `set -e` が素通しした
// 他コマンドの終了コード(tar は致命的エラーで 2 を返す)が意味ありげな値として漏れ、
// 傍らの coding agent はそれを見て誤った次の一手を選ぶ。
var InstallExitCodes = []InstallExitCode{
	{0, "installed"},
	{1, "unexpected failure — unclassified, please report"},
	{2, "unsupported platform (os/arch)"},
	{3, "download failed (dns / tls / proxy / http error / missing asset)"},
	{4, "cannot write to the install prefix (permission, read-only fs, no space)"},
}

// InstallExitCodeLine は終了コード規約の 1 行要約(agent の notes 用)。
func InstallExitCodeLine() string {
	parts := make([]string, 0, len(InstallExitCodes))
	for _, e := range InstallExitCodes {
		parts = append(parts, fmt.Sprintf("%d=%s", e.Code, e.Meaning))
	}
	return "install.sh / install.ps1 exit codes: " + strings.Join(parts, "; ")
}

// AgentDoc は `wharfy agent --json` の出力(schemas/agent.json)。Result envelope とは別形。
// registry から生成するので実体とズレない。
type AgentDoc struct {
	SchemaVersion string       `json:"schema_version"`
	Tool          string       `json:"tool"`
	Version       string       `json:"version"`
	Start         string       `json:"start"`
	StateReaders  []string     `json:"state_readers,omitempty"`
	Commands      []Command    `json:"commands"`
	Channels      []ChannelRef `json:"channels,omitempty"`
}

const schemaVersion = "1"

// selfGeneratorNote は release / publish の注記。install.sh・formula・cask といった生成物は
// 「いま動いている wharfy」が作るので、wharfy 自身をリリースするときだけ、実行中バイナリが repo の
// HEAD から建っていないと HEAD で直した生成器が成果物に入らない。この前提を知らずに --yes を叩けば
// 古い生成器の産物が配られるため、能力マップの側で先に語る(--yes は拒否される)。
const selfGeneratorNote = "when the repo you are releasing is wharfy itself, artifacts are generated by the running binary: " +
	"build it from HEAD first (go build -o /tmp/wharfy ./cmd/wharfy), or --yes is refused (override: --allow-stale-generator)"

// Commands は唯一の真実。順番は「通常の操作順」。
//
// status/build/sign/publish/verify はドメインコマンド。agent/config/version も
// cobra に登録される実コマンドなので、cobra==registry を例外なく成り立たせるため
// ここに含める(「cobra にあるが registry にない」を構造的にゼロにする)。
var Commands = []Command{
	{Name: "agent", Summary: "print this capability map (read once, then drive)", Next: []string{"status"}},
	{Name: "status", Summary: "what is built / signed / published, and where", Next: []string{"build"}},
	{Name: "config", Summary: "show the resolved effective config", Next: []string{"build"}},
	{Name: "auth", Summary: "save a credential (e.g. fury token) to the OS keychain", Args: "<kind>", Next: []string{"publish"}, Notes: []string{
		"--print writes the stored credential to stdout in the form other tools take (the keychain may hold it wrapped), so the credential wharfy uses locally is the one CI gets: wharfy auth fury --print | gh secret set PACKAGE_REPO_TOKEN. it refuses --json — a machine-readable secret ends up in an agent's transcript",
	}},
	{Name: "secrets", Summary: "the credentials and tools your channels need, and how to set them up for CI", Next: []string{"publish"}, Notes: []string{
		"wharfy reads every credential from the environment, so the same commands run on a laptop and in a GitHub Actions workflow",
		"the token GitHub Actions hands a workflow can only write to that repository: channels that write elsewhere (tap, bucket, gated forks) need a PAT registered as a secret",
	}},
	{Name: "init", Summary: "tell agents to release via wharfy (writes AGENTS.md / CLAUDE.md)", Next: []string{"agent"}},
	{Name: "build", Summary: "cross-compile for every os/arch", Next: []string{"sign", "release"}, Notes: []string{
		"the Go build path shells out to goreleaser, so it must be on PATH — on a CI runner install it explicitly (wharfy secrets lists the tools your config needs); BYO inputs (prebuilt: / bundle:) never call it",
	}},
	{Name: "sign", Summary: "codesign macOS binaries with your identity (opt-in; skipped if none)", Next: []string{"release"}},
	{Name: "release", Summary: "upload the github release (archives, packages, install.sh, install.ps1, latest.json)", Next: []string{"publish"}, Notes: []string{
		"re-running it on the same tag is safe: the release is reused and assets already there are replaced, so a workflow that failed at publish can simply be re-run",
		"latest.json carries `latest_json.extra:` from wharfy.yaml verbatim (any JSON value): declare there what is not 'which version is newest' — your app's on-disk data format version, the minimum app version that can read it — and wharfy neither interprets nor validates it; the contract is the reading product's",
		selfGeneratorNote,
	}},
	{Name: "publish", Summary: "push to owned channels; prepare gated ones", Args: "[channel]", Next: []string{"verify"}, Notes: []string{selfGeneratorNote}},
	{Name: "verify", Summary: "check each channel from the consumer side (--install: install from it and run it)", Args: "[channel]", Notes: []string{
		"it needs no local state: with no .wharfy/ record it takes the version from the channels themselves (the latest github release, else the latest git tag), so a bare clone can ask 'does what we shipped still install?' — name the version explicitly with --version <v>",
	}},
	{Name: "version", Summary: "print wharfy's own version (not your project's)", Next: []string{"agent"}},
}

// StateReaders は状態の読み口になるコマンド名(agent の state_readers)。
var StateReaders = []string{"status", "config"}

// Channels は agent が宣伝するチャネル一覧。実装済み Publisher に追従させる(同じ生成思想)。
// homebrew で型を固めた後、低摩擦な goinstall / script から横展開中(§5)。
var Channels = []ChannelRef{
	{Name: "homebrew", Kind: "owned"},
	{Name: "cask", Kind: "owned"},
	{Name: "scoop", Kind: "owned"},
	{Name: "apt", Kind: "owned"},
	{Name: "rpm", Kind: "owned"},
	{Name: "container", Kind: "owned"},
	{Name: "aur", Kind: "owned"},
	{Name: "goinstall", Kind: "owned"},
	{Name: "script", Kind: "owned", Notes: []string{
		"on failure the scripts print the cause and the next move; they never retry, never fall back to a mirror, and never elevate",
		InstallExitCodeLine(),
	}},
	{Name: "winget", Kind: "gated"},
	{Name: "homebrew-core", Kind: "gated"},
}

// Credential は wharfy が環境から読む資格情報 1 つ。
//
// wharfy は資格情報を env からしか取らない(keychain は fury の任意の補助)。だから「手元で export
// する」と「CI にシークレットを登録する」は同じ 1 枚の表で語れる。ここがその表の単一真実。
type Credential struct {
	Env     string `json:"env"`
	Purpose string `json:"purpose"`
	// Secret は「利用者が登録する秘密」か。false は Actions が自前で配るもの(GITHUB_TOKEN)。
	Secret bool `json:"secret"`
}

// Credentials は wharfy が読む env の全て(env 名 → 意味)。
var Credentials = map[string]Credential{
	"GITHUB_TOKEN":             {Env: "GITHUB_TOKEN", Purpose: "upload the release, write your tap/bucket, open gated PRs, push to ghcr"},
	"PACKAGE_REPO_TOKEN":       {Env: "PACKAGE_REPO_TOKEN", Purpose: "push deb/rpm to your hosted package repo", Secret: true},
	"AUR_SSH_KEY":              {Env: "AUR_SSH_KEY", Purpose: "push PKGBUILD to the AUR (the private key itself)", Secret: true},
	"WHARFY_SIGN_P12":          {Env: "WHARFY_SIGN_P12", Purpose: "the Developer ID certificate to codesign macOS binaries with", Secret: true},
	"WHARFY_SIGN_P12_PASSWORD": {Env: "WHARFY_SIGN_P12_PASSWORD", Purpose: "the password of that certificate", Secret: true},
}

// ChannelCredentials はチャネル→そのチャネルが要る env。構成が決まれば要る資格情報は一意に決まる
// ——なので利用者に推測させない。
var ChannelCredentials = map[string][]string{
	"releases":      {"GITHUB_TOKEN"},
	"script":        {"GITHUB_TOKEN"},
	"goinstall":     {"GITHUB_TOKEN"},
	"homebrew":      {"GITHUB_TOKEN"},
	"cask":          {"GITHUB_TOKEN"},
	"scoop":         {"GITHUB_TOKEN"},
	"container":     {"GITHUB_TOKEN"},
	"winget":        {"GITHUB_TOKEN"},
	"homebrew-core": {"GITHUB_TOKEN"},
	"apt":           {"PACKAGE_REPO_TOKEN"},
	"rpm":           {"PACKAGE_REPO_TOKEN"},
	"aur":           {"AUR_SSH_KEY", "GITHUB_TOKEN"},
}

// SignCredentials は署名する場合に要る env(sign: を宣言したときだけ効く)。
var SignCredentials = []string{"WHARFY_SIGN_P12", "WHARFY_SIGN_P12_PASSWORD"}

// Tool は wharfy がサブプロセスとして呼ぶ外部の道具 1 つ。
//
// 資格情報と同じで、構成が決まれば要る道具も一意に決まる——なのに語り口が無かったため、
// 「開発機には入っているから通る」ものが CI の runner で初めて builder_unavailable になった。
// ここが表の単一真実(secrets が構成に照らして要るものだけを出す)。
type Tool struct {
	Bin     string `json:"bin"`
	Purpose string `json:"purpose"`
	// Install は CI の runner へ入れる 1 行(手元にも同じものが効く)。
	Install string `json:"install"`
}

// Tools は wharfy が呼ぶ外部の道具(id → 道具)。git と go は「Go のリポジトリなら在る」ものなので数えない。
var Tools = map[string]Tool{
	"goreleaser": {
		Bin:     "goreleaser",
		Purpose: "cross-compile, archive and package the Go build path — build / release / publish shell out to it (BYO inputs, prebuilt: / bundle:, do not need it)",
		Install: "go install github.com/goreleaser/goreleaser/v2@latest   # or: uses: goreleaser/goreleaser-action@v6 with: {install-only: true}",
	},
	"docker": {
		Bin:     "docker",
		Purpose: "build the multi-arch OCI image and push it to the registry (container channel)",
		Install: "preinstalled on github-hosted runners; elsewhere install docker with buildx",
	},
}

// ToolIDs は Tools の決定的な列挙順(表・注記の並びを安定させる)。
var ToolIDs = []string{"goreleaser", "docker"}

// CheckoutNote は tag から版を決める以上どの workflow でも要る前提。actions/checkout の既定は
// 浅いクローンで tag が来ないため、版が解決できずに release/publish が止まる。
const CheckoutNote = "wharfy takes the version from the git tag: actions/checkout must run with fetch-depth: 0 (its default shallow clone carries no tags)"

// CrossRepoChannels は**自分のリポジトリの外**へ書くチャネルと、その書き先。
//
// GitHub Actions が自前で配る GITHUB_TOKEN は、そのリポジトリにしか書けない。tap も bucket も
// winget/homebrew-core の fork も別リポジトリなので、組み込みトークンでは開かない——PAT を
// シークレットとして登録し、GITHUB_TOKEN として渡す必要がある。ここを黙っていると CI で 403 に
// ぶつかってから調べ直すことになる。
var CrossRepoChannels = map[string]string{
	"homebrew":      "your homebrew tap repo",
	"cask":          "your homebrew tap repo",
	"scoop":         "your scoop bucket repo",
	"winget":        "a fork of microsoft/winget-pkgs",
	"homebrew-core": "a fork of Homebrew/homebrew-core",
}

// ActionsPermissions はチャネル→GitHub Actions の workflow に要る permissions: の行。
var ActionsPermissions = map[string][]string{
	"releases":  {"contents: write"},
	"script":    {"contents: write"},
	"goinstall": {"contents: write"},
	"container": {"contents: write", "packages: write"},
	"aur":       {"contents: write"},
	"homebrew":  {"contents: write"},
	"cask":      {"contents: write"},
	"scoop":     {"contents: write"},
	"apt":       {"contents: write"},
	"rpm":       {"contents: write"},
}

// Names は登録コマンド名の集合。drift テストや next: 参照健全性の照合に使う。
func Names() map[string]bool {
	m := make(map[string]bool, len(Commands))
	for _, c := range Commands {
		m[c.Name] = true
	}
	return m
}

// Lookup は名前でコマンドを引く。無ければ ok=false。
func Lookup(name string) (Command, bool) {
	for _, c := range Commands {
		if c.Name == name {
			return c, true
		}
	}
	return Command{}, false
}

// BuildAgentDoc は registry から agent 出力を生成する(①聞けば分かる)。
// version は cmd 層の versionLine() を渡す(version 注入は package main 側)。
func BuildAgentDoc(version string) AgentDoc {
	return AgentDoc{
		SchemaVersion: schemaVersion,
		Tool:          "wharfy",
		Version:       version,
		Start:         "wharfy status",
		StateReaders:  StateReaders,
		Commands:      Commands,
		Channels:      Channels,
	}
}
