package config

import (
	"fmt"
	"os"
	"path/filepath"
)

// container.go — OCI イメージ(ghcr・マルチアーキ)の生成物(設計 11B)。
// 最小ベース(scratch)にバイナリを載せ、goreleaser dockers + docker_manifests で
// per-arch イメージ＋manifest list を作る。Dockerfile も wharfy が所有する生成物(03)。

const (
	DockerfileName    = "Dockerfile"
	DockerfileRelPath = WharfyDirName + "/" + DockerfileName
)

// GenerateDockerfile は最小 Dockerfile を生成する。goreleaser が build 文脈にバイナリを
// 置くので、プロジェクト名でそのまま COPY する。
func GenerateDockerfile(cfg Config) string {
	binary := cfg.Project
	return fmt.Sprintf(`# GENERATED BY wharfy — do not edit. Minimal image for %[1]s.
# Owned distribution artifact (03_nondestructive_boundary).
FROM scratch
COPY %[1]s /%[1]s
ENTRYPOINT ["/%[1]s"]
`, binary)
}

// WriteDockerfile は Dockerfile を <root>/.wharfy/Dockerfile に書く(root は汚さない・03)。
func WriteDockerfile(root, content string) (string, error) {
	dir := filepath.Join(root, WharfyDirName)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, DockerfileName)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// ContainerImage は container の解決済みイメージ名(無ければ空)。利用者案内に使う。
func ContainerImage(cfg Config) string {
	for _, ch := range cfg.Channels {
		if ch.Name == "container" {
			return ch.Target
		}
	}
	return ""
}
