package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

// sampleConfig は homebrew/releases を含む解決済み設定(生成テストの入力)。
func sampleConfig() Config {
	return Config{
		Project:  "mytool",
		Main:     "./cmd/mytool",
		Github:   "acme/mytool",
		Homepage: "https://github.com/acme/mytool",
		License:  "MIT",
		Channels: []ResolvedChannel{
			{Name: "homebrew", Kind: "owned", Target: "acme/homebrew-mytool"},
			{Name: "releases", Kind: "owned", Target: "acme/mytool"},
			{Name: "goinstall", Kind: "owned", Target: "github.com/acme/mytool"},
		},
		Build: &Build{GOOS: DefaultGOOS, GOARCH: DefaultGOARCH},
	}
}

// parseGen は生成 YAML を緩い map に戻して内容を検証する(GoReleaser スキーマには依存しない)。
func parseGen(t *testing.T, data []byte) map[string]any {
	t.Helper()
	var m map[string]any
	if err := yaml.Unmarshal(data, &m); err != nil {
		t.Fatalf("generated yaml is not parseable: %v\n%s", err, data)
	}
	return m
}

func TestGenerateGoReleaserCore(t *testing.T) {
	data, err := GenerateGoReleaser(sampleConfig(), File{})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(data), "# GENERATED BY wharfy") {
		t.Errorf("missing generated header:\n%s", data)
	}
	m := parseGen(t, data)

	if m["version"] != 2 {
		t.Errorf("version = %v, want 2", m["version"])
	}
	if m["project_name"] != "mytool" {
		t.Errorf("project_name = %v", m["project_name"])
	}

	builds := m["builds"].([]any)
	b0 := builds[0].(map[string]any)
	if b0["main"] != "./cmd/mytool" || b0["binary"] != "mytool" {
		t.Errorf("build main/binary wrong: %+v", b0)
	}
	// version 注入が必ず入る(tag が唯一の真実)。
	ld := toStrings(b0["ldflags"])
	assertContains(t, ld, "-X main.version={{.Version}}")
	assertContains(t, ld, "-X main.commit={{.Commit}}")
	// 既定 env。
	assertContains(t, toStrings(b0["env"]), "CGO_ENABLED=0")
}

func TestGenerateGoReleaserBrew(t *testing.T) {
	data, err := GenerateGoReleaser(sampleConfig(), File{Description: "a tool"})
	if err != nil {
		t.Fatal(err)
	}
	m := parseGen(t, data)
	brews, ok := m["brews"].([]any)
	if !ok || len(brews) != 1 {
		t.Fatalf("expected 1 brew, got %v", m["brews"])
	}
	brew := brews[0].(map[string]any)
	repo := brew["repository"].(map[string]any)
	if repo["owner"] != "acme" || repo["name"] != "homebrew-mytool" {
		t.Errorf("brew repository wrong: %+v", repo)
	}
	if brew["homepage"] != "https://github.com/acme/mytool" || brew["license"] != "MIT" || brew["description"] != "a tool" {
		t.Errorf("brew metadata wrong: %+v", brew)
	}

	release := m["release"].(map[string]any)
	gh := release["github"].(map[string]any)
	if gh["owner"] != "acme" || gh["name"] != "mytool" {
		t.Errorf("release github wrong: %+v", gh)
	}
}

// homebrew が channels に無い / tap 未解決なら brews を出さない(03 所有物のみ)。
func TestGenerateGoReleaserNoBrewWithoutTap(t *testing.T) {
	cfg := sampleConfig()
	cfg.Channels = []ResolvedChannel{{Name: "homebrew", Kind: "owned", Target: ""}} // tap 未解決
	data, err := GenerateGoReleaser(cfg, File{})
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := parseGen(t, data)["brews"]; ok {
		t.Errorf("brews should be omitted when tap is unresolved")
	}
}

func TestGenerateGoReleaserRespectsBuildOverrides(t *testing.T) {
	cfg := sampleConfig()
	cfg.Build = &Build{GOOS: []string{"linux"}, GOARCH: []string{"arm64"}}
	in := File{
		Binary: "mt",
		Build:  &BuildInput{Env: []string{"CGO_ENABLED=1"}, LdflagsExtra: []string{"-X main.extra=1"}},
	}
	m := parseGen(t, mustGen(t, cfg, in))
	b0 := m["builds"].([]any)[0].(map[string]any)
	if b0["binary"] != "mt" {
		t.Errorf("binary override not honored: %v", b0["binary"])
	}
	if !equalAny(b0["goos"], []string{"linux"}) {
		t.Errorf("goos = %v, want [linux]", b0["goos"])
	}
	ld := toStrings(b0["ldflags"])
	assertContains(t, ld, "-X main.extra=1")              // 追加分は後ろに足される
	assertContains(t, ld, "-X main.version={{.Version}}") // 注入は維持
	assertContains(t, toStrings(b0["env"]), "CGO_ENABLED=1")
}

func TestGenerateRequiresMain(t *testing.T) {
	cfg := sampleConfig()
	cfg.Main = ""
	if _, err := GenerateGoReleaser(cfg, File{}); err == nil {
		t.Error("expected error when main is unresolved")
	}
}

// WriteGoReleaser は .wharfy/ に書き、利用者 root には書かない(03)。
func TestWriteGoReleaserNonDestructive(t *testing.T) {
	root := t.TempDir()
	data := []byte("version: 2\n")
	path, err := WriteGoReleaser(root, data)
	if err != nil {
		t.Fatal(err)
	}
	want := filepath.Join(root, ".wharfy", "goreleaser.yaml")
	if path != want {
		t.Errorf("path = %q, want %q", path, want)
	}
	if got, _ := os.ReadFile(path); string(got) != string(data) {
		t.Errorf("written content mismatch")
	}
	// root に .goreleaser.yaml を作っていないこと。
	if _, err := os.Stat(filepath.Join(root, ".goreleaser.yaml")); !os.IsNotExist(err) {
		t.Error("must not write .goreleaser.yaml at repo root")
	}
}

func TestGitignoreNeedsWharfy(t *testing.T) {
	root := t.TempDir()
	if !GitignoreNeedsWharfy(root) {
		t.Error("no .gitignore → should need suggestion")
	}
	os.WriteFile(filepath.Join(root, ".gitignore"), []byte("*.out\nnode_modules/\n"), 0o644)
	if !GitignoreNeedsWharfy(root) {
		t.Error(".wharfy/ absent → should need suggestion")
	}
	os.WriteFile(filepath.Join(root, ".gitignore"), []byte("*.out\n.wharfy/\n"), 0o644)
	if GitignoreNeedsWharfy(root) {
		t.Error(".wharfy/ present → should be idempotent (no suggestion)")
	}
}

// --- helpers ---

func mustGen(t *testing.T, cfg Config, in File) []byte {
	t.Helper()
	data, err := GenerateGoReleaser(cfg, in)
	if err != nil {
		t.Fatal(err)
	}
	return data
}

func toStrings(v any) []string {
	arr, _ := v.([]any)
	out := make([]string, 0, len(arr))
	for _, e := range arr {
		out = append(out, e.(string))
	}
	return out
}

func equalAny(v any, want []string) bool {
	got := toStrings(v)
	if len(got) != len(want) {
		return false
	}
	for i := range got {
		if got[i] != want[i] {
			return false
		}
	}
	return true
}

func assertContains(t *testing.T, hay []string, needle string) {
	t.Helper()
	for _, s := range hay {
		if s == needle {
			return
		}
	}
	t.Errorf("expected %q in %v", needle, hay)
}
