package config

import (
	"fmt"
	"os"
	"path/filepath"
)

// install_script.go — curl|sh インストーラ install.sh を生成する(設計 03/07 script チャネル)。
//
// wharfy が所有する配布物。版固定で、その版のアーカイブを GitHub Releases から取得し bin に入れる。
// goreleaser の release.extra_files で同じ release にアセットとしてアップロードする(別途 push しない)。
// 利用者は `curl -fsSL <releases>/latest/download/install.sh | sh` で入れられる。

// InstallScriptName / InstallScriptRelPath は生成物の場所(.wharfy/ 配下・03)。
const (
	InstallScriptName    = "install.sh"
	InstallScriptRelPath = WharfyDirName + "/" + InstallScriptName
)

// GenerateInstallScript は install.sh を生成する。github(owner/repo)が解決済み前提。
func GenerateInstallScript(cfg Config, version string) string {
	owner, repo, _ := splitOwnerRepo(cfg.Github)
	return fmt.Sprintf(`#!/bin/sh
# GENERATED BY wharfy — do not edit. Installs %[1]s from GitHub Releases.
# Owned distribution artifact (03_nondestructive_boundary).
set -e

PROJECT="%[1]s"
BINARY="%[1]s"
OWNER="%[2]s"
REPO="%[3]s"
VERSION="%[4]s"
PREFIX="${PREFIX:-/usr/local}"

os=$(uname -s | tr '[:upper:]' '[:lower:]')
arch=$(uname -m)
case "$arch" in
  x86_64|amd64) arch=amd64 ;;
  arm64|aarch64) arch=arm64 ;;
  *) echo "wharfy install: unsupported arch: $arch" >&2; exit 1 ;;
esac
case "$os" in
  darwin|linux) ;;
  *) echo "wharfy install: unsupported os: $os" >&2; exit 1 ;;
esac

asset="${PROJECT}_${VERSION}_${os}_${arch}.tar.gz"
url="https://github.com/${OWNER}/${REPO}/releases/download/v${VERSION}/${asset}"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
echo "wharfy install: downloading ${url}"
curl -fsSL "$url" | tar -xz -C "$tmp"
mkdir -p "${PREFIX}/bin"
install -m 0755 "${tmp}/${BINARY}" "${PREFIX}/bin/${BINARY}"
echo "wharfy install: installed ${BINARY} ${VERSION} to ${PREFIX}/bin"
`, cfg.Project, owner, repo, version)
}

// WriteInstallScript は install.sh を <root>/.wharfy/install.sh に書く(root は汚さない・03)。
func WriteInstallScript(root, content string) (string, error) {
	dir := filepath.Join(root, WharfyDirName)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, InstallScriptName)
	if err := os.WriteFile(path, []byte(content), 0o755); err != nil {
		return "", err
	}
	return path, nil
}

// HasChannel は cfg に指定チャネルが含まれるか(生成・発行の分岐に使う)。
func HasChannel(cfg Config, name string) bool {
	for _, ch := range cfg.Channels {
		if ch.Name == name {
			return true
		}
	}
	return false
}

// InstallURL は install.sh の公開 URL。利用者案内・status・probe が使う。
// script.base_url 指定時は解決済みの script チャネル Target(vanity URL)を、
// 未指定なら GitHub Releases の latest アセットを返す(後方互換)。
func InstallURL(cfg Config) string {
	if t := resolvedTarget(cfg, "script"); t != "" {
		return t
	}
	owner, repo, ok := splitOwnerRepo(cfg.Github)
	if !ok {
		return ""
	}
	return fmt.Sprintf("https://github.com/%s/%s/releases/latest/download/%s", owner, repo, InstallScriptName)
}

// resolvedTarget は解決済み cfg.Channels から指定チャネルの Target を引く(無ければ空)。
func resolvedTarget(cfg Config, name string) string {
	for _, ch := range cfg.Channels {
		if ch.Name == name {
			return ch.Target
		}
	}
	return ""
}
