package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func scriptConfig() Config {
	return Config{
		Project: "widget",
		Main:    "./cmd/widget",
		Github:  "acme/widget-demo",
		Channels: []ResolvedChannel{
			{Name: "homebrew", Kind: "owned", Target: "acme/homebrew-widget"},
			{Name: "releases", Kind: "owned", Target: "acme/widget-demo"},
			{Name: "script", Kind: "owned"},
		},
		Build: &Build{GOOS: DefaultGOOS, GOARCH: DefaultGOARCH},
	}
}

func TestGenerateInstallScript(t *testing.T) {
	s := GenerateInstallScript(scriptConfig(), "1.2.3")
	for _, want := range []string{
		"#!/bin/sh",
		"GENERATED BY wharfy",
		`PROJECT="widget"`,
		`OWNER="acme"`,
		`REPO="widget-demo"`,
		`VERSION="1.2.3"`,
		"releases/download/v${VERSION}/${asset}",
		// 既定は per-user(no sudo)。/usr/local は PREFIX 上書きで選ぶ(#15)。
		`PREFIX="${PREFIX:-$HOME/.local}"`,
		`install -m 0755 "${tmp}/${BINARY}" "${PREFIX}/bin/${BINARY}"`,
		// 実行時メッセージは利用者のアプリ名(${PROJECT})を名乗る。
		`echo "${PROJECT}: downloading ${url}"`,
		`echo "${PROJECT}: installed ${BINARY} ${VERSION} to ${PREFIX}/bin"`,
		// PATH 未通なら案内する。
		`is not on your PATH`,
	} {
		if !strings.Contains(s, want) {
			t.Errorf("install.sh missing %q\n---\n%s", want, s)
		}
	}
	// 生成元表示(# GENERATED BY wharfy)以外で "wharfy" が混ざらない
	// (利用者のアプリを入れるスクリプトが wharfy を名乗らない)。
	for _, line := range strings.Split(s, "\n") {
		if strings.HasPrefix(line, "#") {
			continue
		}
		if strings.Contains(line, "wharfy") {
			t.Errorf("install.sh runtime line leaks wharfy: %q", line)
		}
	}
}

func TestGenerateInstallPS1(t *testing.T) {
	s := GenerateInstallPS1(scriptConfig(), "1.2.3")
	for _, want := range []string{
		"GENERATED BY wharfy",
		`$Project   = 'widget'`,
		`$Binary    = 'widget.exe'`,
		`$Owner     = 'acme'`,
		`$Repo      = 'widget-demo'`,
		`$Version   = '1.2.3'`,
		// per-user 既定(admin 不要)。
		`$env:LOCALAPPDATA`,
		// windows zip を os/arch で取りに行く。
		`${Project}_${Version}_windows_${arch}.zip`,
		"releases/download/v$Version/$asset",
		// PATH 未通なら案内。
		"is not on your PATH",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("install.ps1 missing %q\n---\n%s", want, s)
		}
	}
	// PowerShell のエスケープ文字(バックティック)を含まない(Go raw string と衝突しないことの担保)。
	if strings.Contains(s, "`") {
		t.Errorf("install.ps1 must not contain backticks")
	}
}

// 失敗しうる 2 か所(取得・書き込み)が、原因と次の一手を出すこと。
// curl を tar にパイプすると $? は tar のものになり、POSIX sh に pipefail は無いので、
// 分離していること自体が契約(依頼書 doc/wip/request.md §2-1)。
func TestGenerateInstallScriptFailurePaths(t *testing.T) {
	s := GenerateInstallScript(scriptConfig(), "1.2.3")
	if strings.Contains(s, `curl -fsSL "$url" | tar`) {
		t.Error("install.sh must not pipe curl into tar: $? would be tar's, and POSIX sh has no pipefail")
	}
	for _, want := range []string{
		// 取得と展開は別の工程。
		`curl -fsSL "$url" -o "${tmp}/${asset}" || rc=$?`,
		`tar -xzf "${tmp}/${asset}" -C "$tmp" || rc=$?`,
		// 取得失敗は 3 を名乗り、URL と curl の終了コードを出し、手順を案内する。
		`fail 3 "download failed (curl exit ${rc}): ${url}"`,
		"or install it by hand:",
		// 書き込み失敗は 4 を名乗り、逃げ道を 2 つ、打てる 1 行で出す。
		`fail 4 "cannot write ${PREFIX}/bin/${BINARY}"`,
		`curl -fsSL ${INSTALLER} | PREFIX=\"$HOME/.local\" sh`,
		`curl -fsSL ${INSTALLER} | sudo PREFIX=\"${PREFIX}\" sh`,
		// 非対応プラットフォームは 2。
		`fail 2 "unsupported arch: $arch"`,
		`fail 2 "unsupported os: $os"`,
		// 分類できない失敗は 1 に丸め、想定外だと名乗る。fail() が選んだコードだけが素通りする
		// (1..4 だからという理由で通すと、tar の exit 2 が「非対応プラットフォーム」に化ける)。
		`classified=1`,
		`if [ "$classified" -eq 1 ]; then`,
		`echo "${PROJECT}: unexpected failure (exit ${rc})" >&2`,
	} {
		if !strings.Contains(s, want) {
			t.Errorf("install.sh missing %q\n---\n%s", want, s)
		}
	}
	// 自動昇格・自動リトライ・ミラー切替はしない(依頼書 §5)。
	for _, forbidden := range []string{"sudo install", "sudo mkdir", "--retry"} {
		if strings.Contains(s, forbidden) {
			t.Errorf("install.sh must not %q: it changes the user's machine without consent", forbidden)
		}
	}
}

func TestGenerateInstallPS1FailurePaths(t *testing.T) {
	s := GenerateInstallPS1(scriptConfig(), "1.2.3")
	for _, want := range []string{
		`Fail 3 "download failed: $url"`,
		`Fail 4 "cannot write $Binary into $Prefix"`,
		`Fail 2 "unsupported arch: $env:PROCESSOR_ARCHITECTURE"`,
		`Fail 1 "unexpected failure: $($_.Exception.Message)"`,
		// Invoke-WebRequest / Copy-Item にそれぞれ catch がある。
		"  } catch {\n    Fail 3",
		"  } catch {\n    Fail 4",
		// Write-Error は $ErrorActionPreference='Stop' 下で例外になるので使わない。
		"[Console]::Error.WriteLine",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("install.ps1 missing %q\n---\n%s", want, s)
		}
	}
	if strings.Contains(s, "Write-Error") {
		t.Error("install.ps1 must not Write-Error: with ErrorActionPreference=Stop it throws into its own catch")
	}
	// 配列リテラル @(...) の中では ',' が '+' より強く結合する。連結をそこに書くと 1 行が
	// 複数要素に割れ、「打てる 1 行」が打てない形で出る(Windows 実機で踏んだ)。
	// 連結は配列の外(=$rerun)で組み、@(...) の中では変数を置くだけにする。
	if !strings.Contains(s, `$rerun = '  $env:WHARFY_PREFIX = "' + $perUser + '"; irm ' + $Installer + ' | iex'`) {
		t.Error("install.ps1 must build the re-run one-liner outside the array literal")
	}
	elevate := s[strings.Index(s, "$elevate = @("):]
	elevate = elevate[:strings.Index(elevate, "\n)")]
	if strings.Contains(elevate, "' + ") || strings.Contains(elevate, " + '") {
		t.Errorf("install.ps1 $elevate must not concatenate inside @(...): the comma binds tighter than '+'\n%s", elevate)
	}
}

// install.ps1 の URL は install.sh と同じ場所から配られる(base_url があればその配下)。
func TestInstallPS1URL(t *testing.T) {
	if got := InstallPS1URL(scriptConfig()); got != "https://github.com/acme/widget-demo/releases/latest/download/install.ps1" {
		t.Errorf("InstallPS1URL = %q", got)
	}
	cfg := scriptConfig()
	for i, ch := range cfg.Channels {
		if ch.Name == "script" {
			cfg.Channels[i].Target = "https://cdn.example.com/wharfy/install.sh"
		}
	}
	if got := InstallPS1URL(cfg); got != "https://cdn.example.com/wharfy/install.ps1" {
		t.Errorf("InstallPS1URL with base_url = %q", got)
	}
}

func TestWriteInstallPS1NonDestructive(t *testing.T) {
	root := t.TempDir()
	path, err := WriteInstallPS1(root, "# ps1\n")
	if err != nil {
		t.Fatal(err)
	}
	if path != filepath.Join(root, ".wharfy", "install.ps1") {
		t.Errorf("path = %q", path)
	}
	if _, err := os.Stat(filepath.Join(root, "install.ps1")); !os.IsNotExist(err) {
		t.Error("must not write install.ps1 at repo root")
	}
}

func TestInstallURL(t *testing.T) {
	if got := InstallURL(scriptConfig()); got != "https://github.com/acme/widget-demo/releases/latest/download/install.sh" {
		t.Errorf("InstallURL = %q", got)
	}
}

// base_url を配線した script チャネルがあれば InstallURL はその vanity URL を返す。
func TestInstallURLBaseURL(t *testing.T) {
	cfg := scriptConfig()
	for i, ch := range cfg.Channels {
		if ch.Name == "script" {
			cfg.Channels[i].Target = "https://cdn.example.com/wharfy/install.sh"
		}
	}
	if got := InstallURL(cfg); got != "https://cdn.example.com/wharfy/install.sh" {
		t.Errorf("InstallURL with base_url = %q, want the vanity URL", got)
	}
}

func TestWriteInstallScriptNonDestructive(t *testing.T) {
	root := t.TempDir()
	path, err := WriteInstallScript(root, "#!/bin/sh\n")
	if err != nil {
		t.Fatal(err)
	}
	if path != filepath.Join(root, ".wharfy", "install.sh") {
		t.Errorf("path = %q", path)
	}
	if _, err := os.Stat(filepath.Join(root, "install.sh")); !os.IsNotExist(err) {
		t.Error("must not write install.sh at repo root")
	}
}

// script 有効時、生成 GoReleaser 設定の release.extra_files が install.sh を指す。
func TestGenerateGoReleaserScriptExtraFiles(t *testing.T) {
	data, err := GenerateGoReleaser(scriptConfig(), File{})
	if err != nil {
		t.Fatal(err)
	}
	var m map[string]any
	if err := yaml.Unmarshal(data, &m); err != nil {
		t.Fatal(err)
	}
	rel, ok := m["release"].(map[string]any)
	if !ok {
		t.Fatalf("release block missing: %v", m["release"])
	}
	extra, ok := rel["extra_files"].([]any)
	if !ok || len(extra) != 2 {
		t.Fatalf("extra_files should carry install.sh + install.ps1: %v", rel["extra_files"])
	}
	globs := map[string]bool{}
	for _, e := range extra {
		globs[e.(map[string]any)["glob"].(string)] = true
	}
	for _, want := range []string{".wharfy/install.sh", ".wharfy/install.ps1"} {
		if !globs[want] {
			t.Errorf("extra_files missing glob %q (have %v)", want, globs)
		}
	}
}

// script 無効時は extra_files を出さない。
func TestGenerateGoReleaserNoScriptNoExtraFiles(t *testing.T) {
	cfg := scriptConfig()
	cfg.Channels = []ResolvedChannel{{Name: "releases", Kind: "owned", Target: "acme/widget-demo"}}
	data, _ := GenerateGoReleaser(cfg, File{})
	var m map[string]any
	_ = yaml.Unmarshal(data, &m)
	rel, _ := m["release"].(map[string]any)
	if _, ok := rel["extra_files"]; ok {
		t.Errorf("no script → no extra_files, got %v", rel["extra_files"])
	}
}
