package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func scriptConfig() Config {
	return Config{
		Project: "widget",
		Main:    "./cmd/widget",
		Github:  "acme/widget-demo",
		Channels: []ResolvedChannel{
			{Name: "homebrew", Kind: "owned", Target: "acme/homebrew-widget"},
			{Name: "releases", Kind: "owned", Target: "acme/widget-demo"},
			{Name: "script", Kind: "owned"},
		},
		Build: &Build{GOOS: DefaultGOOS, GOARCH: DefaultGOARCH},
	}
}

func TestGenerateInstallScript(t *testing.T) {
	s := GenerateInstallScript(scriptConfig(), "1.2.3")
	for _, want := range []string{
		"#!/bin/sh",
		"GENERATED BY wharfy",
		`PROJECT="widget"`,
		`OWNER="acme"`,
		`REPO="widget-demo"`,
		`VERSION="1.2.3"`,
		"releases/download/v${VERSION}/${asset}",
		`install -m 0755 "${tmp}/${BINARY}" "${PREFIX}/bin/${BINARY}"`,
	} {
		if !strings.Contains(s, want) {
			t.Errorf("install.sh missing %q\n---\n%s", want, s)
		}
	}
}

func TestInstallURL(t *testing.T) {
	if got := InstallURL(scriptConfig()); got != "https://github.com/acme/widget-demo/releases/latest/download/install.sh" {
		t.Errorf("InstallURL = %q", got)
	}
}

// base_url を配線した script チャネルがあれば InstallURL はその vanity URL を返す。
func TestInstallURLBaseURL(t *testing.T) {
	cfg := scriptConfig()
	for i, ch := range cfg.Channels {
		if ch.Name == "script" {
			cfg.Channels[i].Target = "https://cdn.example.com/wharfy/install.sh"
		}
	}
	if got := InstallURL(cfg); got != "https://cdn.example.com/wharfy/install.sh" {
		t.Errorf("InstallURL with base_url = %q, want the vanity URL", got)
	}
}

func TestWriteInstallScriptNonDestructive(t *testing.T) {
	root := t.TempDir()
	path, err := WriteInstallScript(root, "#!/bin/sh\n")
	if err != nil {
		t.Fatal(err)
	}
	if path != filepath.Join(root, ".wharfy", "install.sh") {
		t.Errorf("path = %q", path)
	}
	if _, err := os.Stat(filepath.Join(root, "install.sh")); !os.IsNotExist(err) {
		t.Error("must not write install.sh at repo root")
	}
}

// script 有効時、生成 GoReleaser 設定の release.extra_files が install.sh を指す。
func TestGenerateGoReleaserScriptExtraFiles(t *testing.T) {
	data, err := GenerateGoReleaser(scriptConfig(), File{})
	if err != nil {
		t.Fatal(err)
	}
	var m map[string]any
	if err := yaml.Unmarshal(data, &m); err != nil {
		t.Fatal(err)
	}
	rel, ok := m["release"].(map[string]any)
	if !ok {
		t.Fatalf("release block missing: %v", m["release"])
	}
	extra, ok := rel["extra_files"].([]any)
	if !ok || len(extra) != 1 {
		t.Fatalf("extra_files missing: %v", rel["extra_files"])
	}
	if g := extra[0].(map[string]any)["glob"]; g != ".wharfy/install.sh" {
		t.Errorf("extra_files glob = %v, want .wharfy/install.sh", g)
	}
}

// script 無効時は extra_files を出さない。
func TestGenerateGoReleaserNoScriptNoExtraFiles(t *testing.T) {
	cfg := scriptConfig()
	cfg.Channels = []ResolvedChannel{{Name: "releases", Kind: "owned", Target: "acme/widget-demo"}}
	data, _ := GenerateGoReleaser(cfg, File{})
	var m map[string]any
	_ = yaml.Unmarshal(data, &m)
	rel, _ := m["release"].(map[string]any)
	if _, ok := rel["extra_files"]; ok {
		t.Errorf("no script → no extra_files, got %v", rel["extra_files"])
	}
}
