package config

import (
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ShiroDoromoto/wharfy/internal/registry"
)

// install_script.go — curl|sh インストーラ install.sh を生成する(script チャネル)。
//
// wharfy が所有する配布物。版固定で、その版のアーカイブを GitHub Releases から取得し bin に入れる。
// goreleaser の release.extra_files で同じ release にアセットとしてアップロードする(別途 push しない)。
// 利用者は `curl -fsSL <releases>/latest/download/install.sh | sh` で入れられる。

// InstallScriptName / InstallScriptRelPath は生成物の場所(.wharfy/ 配下)。
const (
	InstallScriptName    = "install.sh"
	InstallScriptRelPath = WharfyDirName + "/" + InstallScriptName
)

// channelNotice は指定チャネルに宣言された告知の文面を返す(無ければ空)。
func channelNotice(cfg Config, channel string) string {
	for _, ch := range cfg.Channels {
		if ch.Name == channel && ch.Deprecated != nil {
			return strings.TrimSpace(ch.Deprecated.Message)
		}
	}
	return ""
}

// shNoticeEchoes は告知を sh の echo 行に直す(1 行 1 echo・stderr)。
// 各行はシングルクォートで括るので $var も `cmd` も評価されない。文面中の ' は '\” で閉じ直す。
// ヒアドキュメントを使わないのは、終端子が文面と衝突する余地を残さないため。
func shNoticeEchoes(notice, indent string) string {
	if notice == "" {
		return ""
	}
	var b strings.Builder
	for _, line := range strings.Split(notice, "\n") {
		fmt.Fprintf(&b, "%secho '%s' >&2\n", indent, strings.ReplaceAll(line, "'", `'\''`))
	}
	return b.String()
}

// ps1NoticeEchoes は告知を PowerShell の Write-Host 行に直す。
// 単一引用文字列なので $var は展開されない。文面中のアポストロフィは 2 つ重ねて escape する。
//
// 非 ASCII の行は base64 にして実行時に UTF-8 として復元する。Windows 同梱の PowerShell 5.1 は
// BOM の無いスクリプトを ANSI コードページで読むため、日本語やアクセント付き文字を直接書くと
// 読み込んだ時点で壊れる(実機で U+7573 が失われることを確認済み)。配布者の言葉を壊さないよう、
// ソースは ASCII だけに保ち、復元は実行時に行う。
func ps1NoticeEchoes(notice string) string {
	if notice == "" {
		return ""
	}
	var b strings.Builder
	for _, line := range strings.Split(notice, "\n") {
		if isASCII(line) {
			fmt.Fprintf(&b, "Write-Host '%s'\n", strings.ReplaceAll(line, "'", "''"))
			continue
		}
		// base64 は ASCII なので、ANSI で読まれても壊れない。
		fmt.Fprintf(&b, "Write-Host ([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('%s')))\n",
			base64.StdEncoding.EncodeToString([]byte(line)))
	}
	return b.String()
}

// isASCII は s が ASCII だけで書かれているか。
func isASCII(s string) bool {
	for _, r := range s {
		if r > 127 {
			return false
		}
	}
	return true
}

// installExitCodeHeader は生成物の冒頭に置く終了コード表を registry から組む。
// 表を生成物・agent・README で別々に手書きすると必ずずれるので、単一真実は registry。
func installExitCodeHeader(commentPrefix string) string {
	var b strings.Builder
	b.WriteString(commentPrefix + " Exit codes (stable; humans and coding agents may branch on these):\n")
	for _, e := range registry.InstallExitCodes {
		fmt.Fprintf(&b, "%s   %d  %s\n", commentPrefix, e.Code, e.Meaning)
	}
	return strings.TrimSuffix(b.String(), "\n")
}

// GenerateInstallScript は install.sh を生成する。github(owner/repo)が解決済み前提。
//
// 失敗しうる箇所ではすべて「何が起きたか」と「次の一手」を出す。ただし出すのは案内であって
// 質問ではない(curl|sh は標準入力がパイプで塞がっており、そもそも問えない)。自動リトライ・
// ミラーへの自動フォールバック・自動昇格はしない — 失敗の原因を隠すか、利用者の同意なく環境を
// 変えるかのどちらかになる。案内の材料は $PROJECT / $url / $asset / $PREFIX だけで、
// 利用側プロジェクト固有の前提は 1 文字も埋めない。
func GenerateInstallScript(cfg Config, version string) string {
	owner, repo, _ := splitOwnerRepo(cfg.Github)
	return fmt.Sprintf(`#!/bin/sh
# GENERATED BY wharfy — do not edit. Installs %[1]s from GitHub Releases.
# Owned distribution artifact.
#
%[6]s
set -e

PROJECT="%[1]s"
BINARY="%[1]s"
OWNER="%[2]s"
REPO="%[3]s"
VERSION="%[4]s"
INSTALLER="%[5]s"
ISSUES="https://github.com/%[2]s/%[3]s/issues"
# per-user by default (no sudo). Override with PREFIX=/usr/local for a system-wide install.
PREFIX="${PREFIX:-$HOME/.local}"

# fail <exit-code> <message> [hint...] — says what happened, then what to do next. Never elevates.
# Sets classified=1 so cleanup knows this exit code carries the meaning we gave it.
classified=0
fail() {
  code=$1
  shift
  echo "${PROJECT}: $1" >&2
  shift
  for hint in "$@"; do
    echo "  $hint" >&2
  done
  classified=1
  exit "$code"
}

os=$(uname -s | tr '[:upper:]' '[:lower:]')
arch=$(uname -m)
case "$arch" in
  x86_64|amd64) arch=amd64 ;;
  arm64|aarch64) arch=arm64 ;;
  *) fail 2 "unsupported arch: $arch" \
       "prebuilt binaries exist for amd64 and arm64 only." \
       "build from source instead: https://github.com/${OWNER}/${REPO}" ;;
esac
case "$os" in
  darwin|linux) ;;
  *) fail 2 "unsupported os: $os" \
       "this installer covers darwin and linux; on windows run install.ps1." ;;
esac

asset="${PROJECT}_${VERSION}_${os}_${arch}.tar.gz"
url="https://github.com/${OWNER}/${REPO}/releases/download/v${VERSION}/${asset}"

command -v curl >/dev/null 2>&1 || fail 3 "curl not found" \
  "install curl, or fetch ${url} by hand and unpack ${BINARY} into ${PREFIX}/bin."

tmp=$(mktemp -d) || fail 1 "cannot create a temporary directory" "please report this: ${ISSUES}"

# Only the codes fail() chose keep their meaning; every other failure is unexpected and says so.
# Passing a code through just because it happens to be 1..4 is how a tar that exits 2 would
# masquerade as "unsupported platform" and send a coding agent down the wrong path.
cleanup() {
  rc=$?
  rm -rf "$tmp"
  if [ "$rc" -eq 0 ]; then
    exit 0
  fi
  if [ "$classified" -eq 1 ]; then
    exit "$rc"
  fi
  echo "${PROJECT}: unexpected failure (exit ${rc})" >&2
  echo "  os=${os} arch=${arch} version=${VERSION}" >&2
  echo "  url=${url}" >&2
  echo "  please report this: ${ISSUES}" >&2
  exit 1
}
trap cleanup EXIT

echo "${PROJECT}: downloading ${url}"
# Downloading and unpacking are separate steps on purpose: piping curl into tar hands $? to tar,
# and POSIX sh has no pipefail, so curl's failure would be invisible to set -e.
rc=0
curl -fsSL "$url" -o "${tmp}/${asset}" || rc=$?
[ "$rc" -eq 0 ] || fail 3 "download failed (curl exit ${rc}): ${url}" \
  "the asset may not exist yet, or dns / tls / a proxy is blocking github." \
  "check with: curl -fsSIL ${url}" \
  "or install it by hand:" \
  "  1. download ${url}" \
  "  2. tar -xzf ${asset}" \
  "  3. mkdir -p ${PREFIX}/bin && install -m 0755 ${BINARY} ${PREFIX}/bin/${BINARY}" \
  "  4. add ${PREFIX}/bin to your PATH"

rc=0
tar -xzf "${tmp}/${asset}" -C "$tmp" || rc=$?
[ "$rc" -eq 0 ] || fail 1 "downloaded archive did not unpack (tar exit ${rc}): ${asset}" \
  "the download may be truncated, or a proxy returned an html page instead of the archive." \
  "please report this: ${ISSUES}"
[ -f "${tmp}/${BINARY}" ] || fail 1 "archive did not contain ${BINARY}: ${asset}" \
  "please report this: ${ISSUES}"

rc=0
mkdir -p "${PREFIX}/bin" || rc=$?
[ "$rc" -eq 0 ] || fail 4 "cannot create ${PREFIX}/bin" \
  "choose a prefix you can write to, or elevate. this installer never elevates for you." \
  "  # install where you already have write access:" \
  "  curl -fsSL ${INSTALLER} | PREFIX=\"$HOME/.local\" sh" \
  "  # or elevate, keeping this prefix:" \
  "  curl -fsSL ${INSTALLER} | sudo PREFIX=\"${PREFIX}\" sh"

rc=0
install -m 0755 "${tmp}/${BINARY}" "${PREFIX}/bin/${BINARY}" || rc=$?
[ "$rc" -eq 0 ] || fail 4 "cannot write ${PREFIX}/bin/${BINARY}" \
  "choose a prefix you can write to, or elevate. this installer never elevates for you." \
  "  # install where you already have write access:" \
  "  curl -fsSL ${INSTALLER} | PREFIX=\"$HOME/.local\" sh" \
  "  # or elevate, keeping this prefix:" \
  "  curl -fsSL ${INSTALLER} | sudo PREFIX=\"${PREFIX}\" sh"

echo "${PROJECT}: installed ${BINARY} ${VERSION} to ${PREFIX}/bin"
case ":$PATH:" in
  *":${PREFIX}/bin:"*) ;;
  *) echo "${PROJECT}: note: ${PREFIX}/bin is not on your PATH; add it: export PATH=\"${PREFIX}/bin:\$PATH\"" >&2 ;;
esac
%[7]s`, cfg.Project, owner, repo, version, InstallURL(cfg), installExitCodeHeader("#"),
		shNoticeEchoes(channelNotice(cfg, "script"), ""))
}

// InstallPS1Name / InstallPS1RelPath は Windows 向け前提物なしインストーラの場所(.wharfy/ 配下)。
// install.sh(mac/Linux)の対で、script チャネルが同じ release に同梱アップロードする。
// 利用者は `irm <releases>/latest/download/install.ps1 | iex` で入れられる。
const (
	InstallPS1Name    = "install.ps1"
	InstallPS1RelPath = WharfyDirName + "/" + InstallPS1Name
)

// GenerateInstallPS1 は install.ps1 を生成する(install.sh の Windows 版)。
// OS 標準の PowerShell だけで動き、per-user(%LOCALAPPDATA%\<project>\bin)に置くので admin 不要。
// 失敗時の作法と終了コードの規約は install.sh と同型(InstallExit* を見よ)。
//
// Write-Error は $ErrorActionPreference='Stop' 下で例外になり、外側 catch に自分で捕まりに行く。
// 案内の出力は [Console]::Error.WriteLine を使う。
func GenerateInstallPS1(cfg Config, version string) string {
	owner, repo, _ := splitOwnerRepo(cfg.Github)
	return fmt.Sprintf(`# GENERATED BY wharfy — do not edit. Installs %[1]s from GitHub Releases.
# Owned distribution artifact.
#
%[6]s
$ErrorActionPreference = 'Stop'

$Project   = '%[1]s'
$Binary    = '%[1]s.exe'
$Owner     = '%[2]s'
$Repo      = '%[3]s'
$Version   = '%[4]s'
$Installer = '%[5]s'
$Issues    = "https://github.com/$Owner/$Repo/issues"
# per-user by default (no admin). Override with $env:WHARFY_PREFIX for another location.
$Prefix  = if ($env:WHARFY_PREFIX) { $env:WHARFY_PREFIX } else { Join-Path $env:LOCALAPPDATA "$Project\bin" }

# Fail — says what happened, then what to do next. Never elevates.
function Fail($Code, $Message, $Hints) {
  [Console]::Error.WriteLine("${Project}: $Message")
  foreach ($h in $Hints) { [Console]::Error.WriteLine("  $h") }
  exit $Code
}

switch ($env:PROCESSOR_ARCHITECTURE) {
  'ARM64' { $arch = 'arm64' }
  'AMD64' { $arch = 'amd64' }
  default { Fail 2 "unsupported arch: $env:PROCESSOR_ARCHITECTURE" @('prebuilt binaries exist for amd64 and arm64 only.') }
}

$asset = "${Project}_${Version}_windows_${arch}.zip"
$url = "https://github.com/$Owner/$Repo/releases/download/v$Version/$asset"
$manual = @(
  'or install it by hand:',
  "  1. download $url",
  '  2. expand the zip',
  "  3. copy $Binary into $Prefix",
  "  4. add $Prefix to your PATH"
)
# Build the one-liner outside the array literal: inside @(...) the comma binds tighter than '+',
# so a concatenation would be split across several elements and the line would not be runnable.
$perUser = Join-Path $env:LOCALAPPDATA "$Project\bin"
$rerun = '  $env:WHARFY_PREFIX = "' + $perUser + '"; irm ' + $Installer + ' | iex'
$elevate = @(
  'choose a prefix you can write to, or elevate. this installer never elevates for you.',
  '  # install where you already have write access:',
  $rerun,
  '  # or run the same line from an elevated (Administrator) PowerShell.'
)

$tmp = Join-Path $env:TEMP ([System.IO.Path]::GetRandomFileName())
New-Item -ItemType Directory -Force -Path $tmp | Out-Null
try {
  Write-Host "${Project}: downloading $url"
  $zip = Join-Path $tmp $asset
  try {
    Invoke-WebRequest -Uri $url -OutFile $zip
  } catch {
    Fail 3 "download failed: $url" (@($_.Exception.Message, 'the asset may not exist yet, or dns / tls / a proxy is blocking github.') + $manual)
  }
  try {
    Expand-Archive -Path $zip -DestinationPath $tmp -Force
  } catch {
    Fail 1 "downloaded archive did not expand: $asset" @($_.Exception.Message, 'the download may be truncated.', "please report this: $Issues")
  }
  if (-not (Test-Path (Join-Path $tmp $Binary))) {
    Fail 1 "archive did not contain ${Binary}: $asset" @("please report this: $Issues")
  }
  try {
    New-Item -ItemType Directory -Force -Path $Prefix | Out-Null
    Copy-Item -Path (Join-Path $tmp $Binary) -Destination (Join-Path $Prefix $Binary) -Force
  } catch {
    Fail 4 "cannot write $Binary into $Prefix" (@($_.Exception.Message) + $elevate)
  }
  Write-Host "${Project}: installed $Binary $Version to $Prefix"
} catch {
  # Anything we did not classify is unexpected, and says so.
  Fail 1 "unexpected failure: $($_.Exception.Message)" @("arch=$arch version=$Version", "url=$url", "please report this: $Issues")
} finally {
  Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue
}

$userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
if (($userPath -split ';') -notcontains $Prefix) {
  Write-Host "${Project}: note: $Prefix is not on your PATH; add it with:"
  Write-Host "  [Environment]::SetEnvironmentVariable('Path', '$Prefix;' + [Environment]::GetEnvironmentVariable('Path','User'), 'User')"
}
%[7]s`, cfg.Project, owner, repo, version, InstallPS1URL(cfg), installExitCodeHeader("#"),
		ps1NoticeEchoes(channelNotice(cfg, "script")))
}

// InstallPS1URL は install.ps1 の公開 URL。script.base_url 指定時はその配下、
// 未指定なら GitHub Releases の latest アセット(InstallURL と同じ既定)。
func InstallPS1URL(cfg Config) string {
	u := InstallURL(cfg)
	if u == "" {
		return ""
	}
	return strings.TrimSuffix(u, InstallScriptName) + InstallPS1Name
}

// WriteInstallPS1 は install.ps1 を <root>/.wharfy/install.ps1 に書く(root は汚さない)。
func WriteInstallPS1(root, content string) (string, error) {
	dir := filepath.Join(root, WharfyDirName)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, InstallPS1Name)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// WriteInstallScript は install.sh を <root>/.wharfy/install.sh に書く(root は汚さない)。
func WriteInstallScript(root, content string) (string, error) {
	dir := filepath.Join(root, WharfyDirName)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, InstallScriptName)
	if err := os.WriteFile(path, []byte(content), 0o755); err != nil {
		return "", err
	}
	return path, nil
}

// HasChannel は cfg に指定チャネルが含まれるか(生成・発行の分岐に使う)。
func HasChannel(cfg Config, name string) bool {
	for _, ch := range cfg.Channels {
		if ch.Name == name {
			return true
		}
	}
	return false
}

// InstallURL は install.sh の公開 URL。利用者案内・status・probe が使う。
// script.base_url 指定時は解決済みの script チャネル Target(vanity URL)を、
// 未指定なら GitHub Releases の latest アセットを返す(後方互換)。
func InstallURL(cfg Config) string {
	if t := resolvedTarget(cfg, "script"); t != "" {
		return t
	}
	owner, repo, ok := splitOwnerRepo(cfg.Github)
	if !ok {
		return ""
	}
	return fmt.Sprintf("https://github.com/%s/%s/releases/latest/download/%s", owner, repo, InstallScriptName)
}

// ReleaseAssetURL は「そのタグの Release に上がっている資産」の URL(tag 直リンク)。
// latest 経由(InstallURL)と違い、昇格していない版の資産もそのまま引ける —— 昇格前に
// 「これから配る実物」を確かめられるのはこの URL だけ(D-263: 検証の窓は prerelease で開く)。
// github が解決できなければ空。
func ReleaseAssetURL(cfg Config, version, name string) string {
	owner, repo, ok := splitOwnerRepo(cfg.Github)
	if !ok {
		return ""
	}
	return fmt.Sprintf("https://github.com/%s/%s/releases/download/v%s/%s", owner, repo, strings.TrimPrefix(version, "v"), name)
}

// resolvedTarget は解決済み cfg.Channels から指定チャネルの Target を引く(無ければ空)。
func resolvedTarget(cfg Config, name string) string {
	for _, ch := range cfg.Channels {
		if ch.Name == name {
			return ch.Target
		}
	}
	return ""
}
