package config

import (
	"fmt"
	"os"
	"path/filepath"
)

// install_script.go — curl|sh インストーラ install.sh を生成する(設計 03/07 script チャネル)。
//
// wharfy が所有する配布物。版固定で、その版のアーカイブを GitHub Releases から取得し bin に入れる。
// goreleaser の release.extra_files で同じ release にアセットとしてアップロードする(別途 push しない)。
// 利用者は `curl -fsSL <releases>/latest/download/install.sh | sh` で入れられる。

// InstallScriptName / InstallScriptRelPath は生成物の場所(.wharfy/ 配下・03)。
const (
	InstallScriptName    = "install.sh"
	InstallScriptRelPath = WharfyDirName + "/" + InstallScriptName
)

// GenerateInstallScript は install.sh を生成する。github(owner/repo)が解決済み前提。
func GenerateInstallScript(cfg Config, version string) string {
	owner, repo, _ := splitOwnerRepo(cfg.Github)
	return fmt.Sprintf(`#!/bin/sh
# GENERATED BY wharfy — do not edit. Installs %[1]s from GitHub Releases.
# Owned distribution artifact (03_nondestructive_boundary).
set -e

PROJECT="%[1]s"
BINARY="%[1]s"
OWNER="%[2]s"
REPO="%[3]s"
VERSION="%[4]s"
# per-user by default (no sudo). Override with PREFIX=/usr/local for a system-wide install.
PREFIX="${PREFIX:-$HOME/.local}"

os=$(uname -s | tr '[:upper:]' '[:lower:]')
arch=$(uname -m)
case "$arch" in
  x86_64|amd64) arch=amd64 ;;
  arm64|aarch64) arch=arm64 ;;
  *) echo "${PROJECT}: unsupported arch: $arch" >&2; exit 1 ;;
esac
case "$os" in
  darwin|linux) ;;
  *) echo "${PROJECT}: unsupported os: $os" >&2; exit 1 ;;
esac

asset="${PROJECT}_${VERSION}_${os}_${arch}.tar.gz"
url="https://github.com/${OWNER}/${REPO}/releases/download/v${VERSION}/${asset}"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
echo "${PROJECT}: downloading ${url}"
curl -fsSL "$url" | tar -xz -C "$tmp"
mkdir -p "${PREFIX}/bin"
install -m 0755 "${tmp}/${BINARY}" "${PREFIX}/bin/${BINARY}"
echo "${PROJECT}: installed ${BINARY} ${VERSION} to ${PREFIX}/bin"
case ":$PATH:" in
  *":${PREFIX}/bin:"*) ;;
  *) echo "${PROJECT}: note: ${PREFIX}/bin is not on your PATH; add it: export PATH=\"${PREFIX}/bin:\$PATH\"" >&2 ;;
esac
`, cfg.Project, owner, repo, version)
}

// InstallPS1Name / InstallPS1RelPath は Windows 向け前提物なしインストーラの場所(.wharfy/ 配下)。
// install.sh(mac/Linux)の対で、script チャネルが同じ release に同梱アップロードする。
// 利用者は `irm <releases>/latest/download/install.ps1 | iex` で入れられる。
const (
	InstallPS1Name    = "install.ps1"
	InstallPS1RelPath = WharfyDirName + "/" + InstallPS1Name
)

// GenerateInstallPS1 は install.ps1 を生成する(install.sh の Windows 版)。
// OS 標準の PowerShell だけで動き、per-user(%LOCALAPPDATA%\<project>\bin)に置くので admin 不要。
func GenerateInstallPS1(cfg Config, version string) string {
	owner, repo, _ := splitOwnerRepo(cfg.Github)
	return fmt.Sprintf(`# GENERATED BY wharfy — do not edit. Installs %[1]s from GitHub Releases.
# Owned distribution artifact (03_nondestructive_boundary).
$ErrorActionPreference = 'Stop'

$Project = '%[1]s'
$Binary  = '%[1]s.exe'
$Owner   = '%[2]s'
$Repo    = '%[3]s'
$Version = '%[4]s'
# per-user by default (no admin). Override with $env:WHARFY_PREFIX for another location.
$Prefix  = if ($env:WHARFY_PREFIX) { $env:WHARFY_PREFIX } else { Join-Path $env:LOCALAPPDATA "$Project\bin" }

switch ($env:PROCESSOR_ARCHITECTURE) {
  'ARM64' { $arch = 'arm64' }
  'AMD64' { $arch = 'amd64' }
  default { Write-Error "$Project: unsupported arch: $env:PROCESSOR_ARCHITECTURE"; exit 1 }
}

$asset = "${Project}_${Version}_windows_${arch}.zip"
$url = "https://github.com/$Owner/$Repo/releases/download/v$Version/$asset"
$tmp = Join-Path $env:TEMP ([System.IO.Path]::GetRandomFileName())
New-Item -ItemType Directory -Force -Path $tmp | Out-Null
try {
  Write-Host "${Project}: downloading $url"
  $zip = Join-Path $tmp $asset
  Invoke-WebRequest -Uri $url -OutFile $zip
  Expand-Archive -Path $zip -DestinationPath $tmp -Force
  New-Item -ItemType Directory -Force -Path $Prefix | Out-Null
  Copy-Item -Path (Join-Path $tmp $Binary) -Destination (Join-Path $Prefix $Binary) -Force
  Write-Host "${Project}: installed $Binary $Version to $Prefix"
} finally {
  Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue
}

$userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
if (($userPath -split ';') -notcontains $Prefix) {
  Write-Host "${Project}: note: $Prefix is not on your PATH; add it with:"
  Write-Host "  [Environment]::SetEnvironmentVariable('Path', '$Prefix;' + [Environment]::GetEnvironmentVariable('Path','User'), 'User')"
}
`, cfg.Project, owner, repo, version)
}

// WriteInstallPS1 は install.ps1 を <root>/.wharfy/install.ps1 に書く(root は汚さない・03)。
func WriteInstallPS1(root, content string) (string, error) {
	dir := filepath.Join(root, WharfyDirName)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, InstallPS1Name)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// WriteInstallScript は install.sh を <root>/.wharfy/install.sh に書く(root は汚さない・03)。
func WriteInstallScript(root, content string) (string, error) {
	dir := filepath.Join(root, WharfyDirName)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, InstallScriptName)
	if err := os.WriteFile(path, []byte(content), 0o755); err != nil {
		return "", err
	}
	return path, nil
}

// HasChannel は cfg に指定チャネルが含まれるか(生成・発行の分岐に使う)。
func HasChannel(cfg Config, name string) bool {
	for _, ch := range cfg.Channels {
		if ch.Name == name {
			return true
		}
	}
	return false
}

// InstallURL は install.sh の公開 URL。利用者案内・status・probe が使う。
// script.base_url 指定時は解決済みの script チャネル Target(vanity URL)を、
// 未指定なら GitHub Releases の latest アセットを返す(後方互換)。
func InstallURL(cfg Config) string {
	if t := resolvedTarget(cfg, "script"); t != "" {
		return t
	}
	owner, repo, ok := splitOwnerRepo(cfg.Github)
	if !ok {
		return ""
	}
	return fmt.Sprintf("https://github.com/%s/%s/releases/latest/download/%s", owner, repo, InstallScriptName)
}

// resolvedTarget は解決済み cfg.Channels から指定チャネルの Target を引く(無ければ空)。
func resolvedTarget(cfg Config, name string) string {
	for _, ch := range cfg.Channels {
		if ch.Name == name {
			return ch.Target
		}
	}
	return ""
}
