// selfrelease.go — 生成器の版ズレ検知。
//
// 生成物(install.sh / install.ps1 / formula / cask …)は「いま動いている wharfy」が作る。
// だから wharfy 自身の repo を古い wharfy でリリースすると、HEAD で直したばかりの生成器が
// 成果物に入らない(v0.16.0 の install.ps1 が、直っていたのに壊れたまま配られた)。
// release / publish の入口でこれを検知し、HEAD からビルドし直す手順を next に出す。
// plan(--yes なし)では警告どまり、apply(--yes)では実アップロードの前に拒否する。
//
// 対象は「実行中バイナリと同じ module を宣言する repo」に限る。他人のプロジェクトでは
// 生成器は常に別リポの wharfy が持つので、この食い違いは原理的に起きない。
package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime/debug"
	"strings"

	"github.com/ShiroDoromoto/wharfy/internal/output"
	"github.com/ShiroDoromoto/wharfy/internal/registry"
)

// 実行中バイナリの素性。テストで差し替えるため変数にしている。
var (
	selfModulePath = buildModulePath
	selfRevision   = buildRevision
)

// buildModulePath は実行中バイナリの main モジュールパス(取れなければ空)。
func buildModulePath() string {
	if info, ok := debug.ReadBuildInfo(); ok {
		return info.Main.Path
	}
	return ""
}

// buildRevision は実行中バイナリがビルドされた commit。
// リリース版は ldflags 注入から、go build 直のバイナリは vcs.revision から来る。
// どちらも無ければ空(= 素性不明)。
func buildRevision() string {
	if _, c, _ := resolveVersion(); c != "" {
		return c
	}
	if info, ok := debug.ReadBuildInfo(); ok {
		for _, s := range info.Settings {
			if s.Key == "vcs.revision" {
				return s.Value
			}
		}
	}
	return ""
}

// moduleOfDir は dir の go.mod が宣言する module path(読めなければ空)。
// 「リリース対象が wharfy 自身か」を判定する唯一の材料。
func moduleOfDir(dir string) string {
	data, err := os.ReadFile(filepath.Join(dir, "go.mod"))
	if err != nil {
		return ""
	}
	for _, ln := range strings.Split(string(data), "\n") {
		rest, ok := strings.CutPrefix(strings.TrimSpace(ln), "module ")
		if !ok {
			continue
		}
		return strings.Trim(strings.TrimSpace(rest), `"`)
	}
	return ""
}

// gitHeadRevision は dir の HEAD が指す commit(git が無い/repo でないなら空)。
func gitHeadRevision(dir string) string {
	out, err := exec.Command("git", "-C", dir, "rev-parse", "HEAD").Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}

// staleGeneratorMessage は生成器の版ズレを説明する 1 行を返す(ズレていなければ空)。
// 判定材料が欠けたときは黙る——誤検知で他人のリリースを騒がせない方が大事なので、
// 「わからない」は「ズレている」ではなく「言わない」に倒す。
func staleGeneratorMessage(selfModule, selfRev, repoModule, repoHead string) string {
	if selfModule == "" || repoModule == "" || selfModule != repoModule {
		return "" // wharfy 自身の repo ではない — 生成器は別リポにあり、ズレようがない
	}
	if repoHead == "" {
		return "" // git が無い/repo でない — HEAD と比べようがない
	}
	if selfRev == "" {
		return "running wharfy carries no build revision, so it may not come from this repo's HEAD (" +
			shortRevision(repoHead) + "); artifacts are generated by the running binary"
	}
	if selfRev == repoHead {
		return ""
	}
	return "running wharfy was built from " + shortRevision(selfRev) + " but this repo's HEAD is " +
		shortRevision(repoHead) + "; artifacts are generated by the running binary, so fixes at HEAD won't ship"
}

func shortRevision(rev string) string {
	if len(rev) > 7 {
		return rev[:7]
	}
	return rev
}

// withStaleGeneratorWarning は版ズレを結果に載せる。plan 経路(--yes なし)では警告どまりでよい——
// まだ何も配っておらず、読んだ人間が建て直すか進むかを選べるため。ズレていなければ何も足さない。
// apply 経路は staleGeneratorRefusal が先に止めるので、ここに届く apply は明示上書き済みのものだけ。
func withStaleGeneratorWarning(root string, c registry.Command, res output.Result) output.Result {
	msg := staleGeneratorMessage(selfModulePath(), selfRevision(), moduleOfDir(root), gitHeadRevision(root))
	if msg == "" {
		return res
	}
	res.Warnings = append(res.Warnings, output.Warning{Code: output.WarnStaleGenerator, Message: msg})
	res.Next = append(res.Next, output.NextDo{
		Reason: "generate artifacts with the generator at HEAD, not the installed wharfy",
		Do:     "go build -o /tmp/wharfy ./cmd/wharfy && /tmp/wharfy " + c.Name,
	})
	return res
}

// staleGeneratorRefusal は apply(--yes)を版ズレのまま走らせようとしたときの拒否(2 番目の戻り値が true)。
//
// 警告では防げない: --yes は非対話なので、警告が読まれる頃には古い生成器が作った install.ps1 や
// formula がもう GitHub Release に上がっている。判断できる時点は「アップロードの前」しかない。
// 意図して手元の版で配る運用のために --allow-stale-generator を逃げ道に残す(配布は明示ゲート)。
// 発火するのは wharfy 自身の repo だけ(staleGeneratorMessage が module path で絞る)。
func staleGeneratorRefusal(root string, c registry.Command) (output.Result, bool) {
	if flagAllowStale {
		return output.Result{}, false
	}
	msg := staleGeneratorMessage(selfModulePath(), selfRevision(), moduleOfDir(root), gitHeadRevision(root))
	if msg == "" {
		return output.Result{}, false
	}
	res := output.New(c.Name, "refusing to "+c.Name+" with a stale generator", false)
	res.Errors = []output.Problem{{
		Code:    output.ErrStaleGeneratorBlocked,
		Message: msg,
		Hint:    "build from HEAD and rerun, or pass --allow-stale-generator to ship what the running binary generates",
	}}
	res.Next = []output.NextDo{
		{
			Reason: "generate artifacts with the generator at HEAD, not the installed wharfy",
			Do:     "go build -o /tmp/wharfy ./cmd/wharfy && /tmp/wharfy " + c.Name + " --yes",
		},
		{
			Reason: "intentionally ship the running binary's generators",
			Do:     "wharfy " + c.Name + " --yes --allow-stale-generator",
		},
	}
	return res, true
}
